import path from 'node:path';

/**
 * @param {string} markdown
 * @param {{ githubRepo: string, branch: string, locale: 'en' | 'pt-BR' }} options
 * @returns {string}
 */
export function transformReadme(markdown, options) {
  const {githubRepo, branch, locale} = options;
  let body = markdown.replace(/\r\n/g, '\n');

  body = stripCoverImage(body);
  body = stripBadgeRows(body);
  body = stripLocaleSwitchBlockquotes(body);
  body = collapseLeadingBlankLines(body);
  body = rewriteRelativeUrls(body, githubRepo, branch);

  const title = locale === 'en' ? 'Getting started' : 'Primeiros passos';

  return `---
id: getting-started
title: ${title}
sidebar_position: 1
slug: /
---

{/* AUTO-GENERATED by scripts/sync-readmes.mjs. Do not edit this file. */}

${body.trimStart()}`;
}

function stripCoverImage(markdown) {
  return markdown.replace(
    /^(?:\s*\n)*!\[[^\]]*\]\(([^)]+)\)\s*\n+/,
    (full, url) => {
      const altMatch = full.match(/^!\[[^\]]*\]/);
      const alt = altMatch ? altMatch[0] : '';
      if (
        /\/img\/cover_|cover_br-utils/i.test(url) ||
        /br-utils|br-utilities/i.test(alt)
      ) {
        return '';
      }
      return full;
    },
  );
}

function stripBadgeRows(markdown) {
  const lines = markdown.split('\n');
  let i = 0;
  while (i < lines.length && lines[i].trim() === '') {
    i += 1;
  }
  const start = i;
  while (i < lines.length && /^\[!\[/.test(lines[i].trim())) {
    i += 1;
  }
  if (i > start) {
    lines.splice(start, i - start);
  }
  return lines.join('\n');
}

function stripLocaleSwitchBlockquotes(markdown) {
  const patterns = [
    /Acessar documentação em português/i,
    /Access documentation in English/i,
    /documentação em português/i,
    /documentation in English/i,
  ];
  const lines = markdown.split('\n');
  const out = [];
  for (const line of lines) {
    const isQuote = /^\s*>/.test(line);
    if (isQuote && patterns.some((re) => re.test(line))) {
      continue;
    }
    out.push(line);
  }
  return out.join('\n');
}

function collapseLeadingBlankLines(markdown) {
  return markdown.replace(/^\s+/, '').replace(/\n{3,}/g, '\n\n');
}

function rewriteRelativeUrls(markdown, githubRepo, branch) {
  return markdown.replace(
    /(!?\[[^\]]*\]\()([^)\s]+)(\))/g,
    (full, prefix, url, suffix) => {
      if (
        /^(https?:|mailto:|#|\/\/)/i.test(url) ||
        url.startsWith('data:')
      ) {
        return full;
      }
      const hashIndex = url.indexOf('#');
      const hash = hashIndex >= 0 ? url.slice(hashIndex) : '';
      const rawPath = hashIndex >= 0 ? url.slice(0, hashIndex) : url;
      const normalized = path.posix
        .normalize(rawPath)
        .replace(/^\.\//, '')
        .replace(/^\/+/, '');
      const isImage = /\.(png|jpe?g|gif|svg|webp)$/i.test(normalized);
      const dest = isImage
        ? `https://raw.githubusercontent.com/${githubRepo}/${branch}/${normalized}`
        : `https://github.com/${githubRepo}/blob/${branch}/${normalized}`;
      return `${prefix}${dest}${hash}${suffix}`;
    },
  );
}
